version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: alvara_db_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: alvara_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${SPRING_RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${SPRING_RABBITMQ_PASSWORD}

  backend:
    container_name: alvara_api_backend
    build: .
    ports:
      - "8080:8080"
    environment:
      # Conexão com o Banco de Dados
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # Credenciais do Admin Inicial
      APP_INITIAL_ADMIN_LOGIN: ${ADMIN_LOGIN}
      APP_INITIAL_ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Segredos da Aplicação
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET}
      API_TASK_KEY: ${API_TASK_KEY}

      # Configuração de E-mail
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}

      # Configuração do RabbitMQ
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}

      # Configurações de Funcionalidades
      PLANILHA_URL: ${PLANILHA_URL}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      APP_NOTIFICATIONS_ENABLED: ${APP_NOTIFICATIONS_ENABLED}
      APP_CORS_ALLOWEDORIGINS: ${APP_CORS_ALLOWEDORIGINS}
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data: