server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

  # Ativa o perfil 'dev' por padrao. Isso fara o Spring procurar por um arquivo application-dev.yml
  profiles:
    active: dev
